# Generated by Django 4.2.6 on 2024-08-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='会社名')),
                ('employee_count', models.CharField(max_length=200, verbose_name='社員数')),
                ('url', models.URLField(verbose_name='会社URL')),
                ('overtime', models.CharField(max_length=200, verbose_name='残業')),
                ('salary', models.CharField(max_length=200, verbose_name='給料')),
                ('salary_increase', models.CharField(max_length=200, verbose_name='昇給')),
                ('working_conditions', models.TextField(verbose_name='勤務条件')),
                ('employee_benefits', models.TextField(verbose_name='福利厚生')),
                ('paid_leave_utilization_rate', models.CharField(max_length=200, verbose_name='有休消化率')),
                ('engineering_field', models.CharField(choices=[('frontend_engineer', 'フロントエンジニア'), ('backend_engineer', 'バックエンドエンジニア'), ('fullstack_engineer', 'フルスタックエンジニア'), ('devops_engineer', 'デベロップメントエンジニア'), ('sitereliability_engineer', 'サイトリライアビリティエンジニア')], max_length=50, verbose_name='エンジニア領域')),
                ('programming_language', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('go', 'Go'), ('miscellaneous', 'その他')], max_length=50, verbose_name='使用言語')),
                ('training', models.CharField(choices=[('yes', 'あり'), ('no', 'なし')], max_length=3, verbose_name='研修制度')),
                ('growth_environment', models.CharField(choices=[('five', '★★★★★(充実)'), ('four', '★★★★'), ('three', '★★★'), ('two', '★★'), ('one', '★(なし)')], max_length=10, verbose_name='成長環境(忙しさ)')),
                ('strengths', models.TextField(verbose_name='強み')),
                ('weaknesses', models.TextField(verbose_name='弱み')),
                ('work_life_balance', models.TextField(verbose_name='ワークライフバランス')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
