# Generated by Django 4.2.6 on 2024-08-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='strengths',
        ),
        migrations.AddField(
            model_name='company',
            name='first_choice',
            field=models.BooleanField(default=False, verbose_name='第一志望'),
        ),
        migrations.AddField(
            model_name='company',
            name='second_choice',
            field=models.BooleanField(default=False, verbose_name='第二志望'),
        ),
        migrations.AddField(
            model_name='company',
            name='third_choice',
            field=models.BooleanField(default=False, verbose_name='第三志望'),
        ),
        migrations.AlterField(
            model_name='company',
            name='engineering_field',
            field=models.CharField(choices=[('frontend_engineer', 'フロントエンジニア'), ('backend_engineer', 'バックエンドエンジニア'), ('fullstack_engineer', 'フルスタックエンジニア'), ('deveopments_engineer', 'デベロップメントエンジニア'), ('sitereliability_engineer', 'サイトリライアビリティエンジニア')], max_length=50, verbose_name='エンジニア領域'),
        ),
        migrations.AlterField(
            model_name='company',
            name='training',
            field=models.CharField(choices=[('yes', 'あり'), ('no', 'なし')], max_length=10, verbose_name='研修制度'),
        ),
    ]
