# Generated by Django 4.2.6 on 2024-08-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_company_strengths_company_first_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='growth_environment',
            field=models.CharField(choices=[('five', '★★★★★(忙しい)'), ('four', '★★★★'), ('three', '★★★'), ('two', '★★'), ('one', '★(簡単)')], max_length=10, verbose_name='成長環境(忙しさ)'),
        ),
    ]
