# Generated by Django 4.2.6 on 2024-08-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_company_growth_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='advantage',
            field=models.TextField(default='特になし', max_length=200, verbose_name='強み'),
        ),
        migrations.AlterField(
            model_name='company',
            name='weaknesses',
            field=models.TextField(default='特になし', max_length=200, verbose_name='弱み'),
        ),
    ]
