# Generated by Django 4.2.6 on 2024-08-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_company_advantage_alter_company_weaknesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='allowance',
            field=models.TextField(default='特になし', verbose_name='各種手当'),
        ),
        migrations.AlterField(
            model_name='company',
            name='overtime',
            field=models.CharField(max_length=200, verbose_name='平均残業時間'),
        ),
    ]
