# Generated by Django 4.2.6 on 2024-08-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_company_allowance_alter_company_overtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bonuses',
            field=models.CharField(default='', max_length=200, verbose_name='賞与'),
        ),
        migrations.AddField(
            model_name='company',
            name='holidays_and_vacations',
            field=models.CharField(default='', max_length=200, verbose_name='休日休暇'),
        ),
        migrations.AddField(
            model_name='company',
            name='place_of_work',
            field=models.TextField(default='', verbose_name='就業場所'),
        ),
        migrations.AddField(
            model_name='company',
            name='working_hours',
            field=models.TextField(default='', verbose_name='就業時間'),
        ),
        migrations.AlterField(
            model_name='company',
            name='allowance',
            field=models.TextField(default='特になし', verbose_name='諸手当'),
        ),
        migrations.AlterField(
            model_name='company',
            name='salary',
            field=models.CharField(max_length=200, verbose_name='基本給'),
        ),
    ]
