# Generated by Django 4.2.6 on 2024-08-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_company_bonuses_company_holidays_and_vacations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ways_of_working',
            field=models.CharField(choices=[('flex_time', 'フレックスタイム制 - 働く時間を柔軟に調整できる制度'), ('short_hours', '時短勤務 - 通常の労働時間より短い勤務時間'), ('shift_work', 'シフト勤務 - 複数のシフトを組み合わせて勤務する方法'), ('core_time', 'コアタイム制 - 一部の時間帯は必ず勤務することが求められる制度'), ('remote_work', 'テレワーク - 自宅やその他のリモートな場所からの勤務'), ('hybrid_work', 'ハイブリッド勤務 - オフィスとリモートの両方を組み合わせて働く方法'), ('free_address', 'フリーアドレス - 自由な座席を選べるオフィス勤務の形態'), ('part_time', 'パートタイム勤務 - 通常のフルタイムより短い勤務時間で働く方法'), ('discretionary_work', '裁量労働制 - 労働時間の裁量が社員に委ねられる制度'), ('digital_nomad', 'デジタルノマド - インターネットを利用して世界中どこでも働くスタイル')], default='flex_time', max_length=18, verbose_name='働き方'),
        ),
    ]
