# Generated by Django 4.2.6 on 2024-08-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_company_ways_of_working'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='working_conditions',
        ),
    ]
