# Generated by Django 4.2.6 on 2024-08-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_company_working_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='engineering_field',
            field=models.CharField(choices=[('frontend_engineer', 'フロントエンジニア(ウェブ開発) - デザインと実装を担当。HTML, CSS, JavaScriptを使用して、ユーザーが直接触れる部分を作成する。'), ('backend_engineer', 'バックエンドエンジニア(ソフトウェア開発、データベース管理) - ロジックやデータベースの設計・実装を担当。APIの設計やデータ処理、サーバーの運用管理を行う。'), ('fullstack_engineer', 'フルスタックエンジニア(フロントとバックエンドのハーフ) - ウェブアプリケーション全体の設計と実装を担当。幅広い技術スキルが求められる。'), ('deveopments_engineer', 'デベロップメントエンジニア(ソフトウェア開発、プログラミング) - ソフトウェアの設計・開発を担当。基本的にはプログラミング全般に関わる。'), ('sitereliability_engineer', 'サイトリライアビリティエンジニア(システム管理、クラウドコンピューティング、ネットワークエンジニアリング、セキュリティ) - システムの運用と監視を行い、障害対応やパフォーマンスの最適化に注力すする。')], max_length=50, verbose_name='エンジニア領域'),
        ),
    ]
