# Generated by Django 4.2.6 on 2024-09-02 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_company_fourth_choice_company_other_choice_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='first_choice',
        ),
        migrations.RemoveField(
            model_name='company',
            name='fourth_choice',
        ),
        migrations.RemoveField(
            model_name='company',
            name='other_choice',
        ),
        migrations.RemoveField(
            model_name='company',
            name='second_choice',
        ),
        migrations.RemoveField(
            model_name='company',
            name='third_choice',
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_level', models.PositiveSmallIntegerField(choices=[(1, '第一志望'), (2, '第二志望'), (3, '第三志望'), (4, '第四志望'), (5, 'その他')])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
