# Generated by Django 4.2.6 on 2024-09-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_companynote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employee_count',
            field=models.IntegerField(verbose_name='社員数'),
        ),
        migrations.AlterField(
            model_name='company',
            name='overtime',
            field=models.IntegerField(verbose_name='平均残業時間'),
        ),
        migrations.AlterField(
            model_name='company',
            name='paid_leave_utilization_rate',
            field=models.IntegerField(verbose_name='有休消化率'),
        ),
        migrations.AlterField(
            model_name='company',
            name='salary',
            field=models.IntegerField(verbose_name='基本給'),
        ),
    ]
