# Generated by Django 5.1.1 on 2024-09-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_company_employee_count_alter_company_overtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='就業場所')),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='engineering_field',
            field=models.CharField(choices=[('frontend_engineer', 'フロントエンジニア(ウェブ開発) - デザインと実装を担当。HTML, CSS, JavaScriptを使用して、ユーザーが直接触れる部分を作成する。'), ('backend_engineer', 'バックエンドエンジニア(ソフトウェア開発、データベース管理) - ロジックやデータベースの設計・実装を担当。APIの設計やデータ処理、サーバーの運用管理を行う。'), ('fullstack_engineer', 'フルスタックエンジニア(フロントとバックエンドのハーフ) - ウェブアプリケーション全体の設計と実装を担当。幅広い技術スキルが求められる。'), ('deveopments_engineer', 'デベロップメントエンジニア(ソフトウェア開発、プログラミング) - ソフトウェアの設計・開発を担当。基本的にはプログラミング全般に関わる。'), ('sitereliability_engineer', 'サイトリライアビリティエンジニア(システム管理、クラウドコンピューティング、ネットワークエンジニアリング、セキュリティ) - システムの運用と監視を行い、障害対応やパフォーマンスの最適化に注力すする。'), ('unknown', '不明')], max_length=50, verbose_name='エンジニア領域'),
        ),
        migrations.RemoveField(
            model_name='company',
            name='place_of_work',
        ),
        migrations.AlterField(
            model_name='preference',
            name='preference_level',
            field=models.PositiveSmallIntegerField(choices=[(1, '第一志望'), (2, '第二志望'), (3, '第三志望'), (4, '第四志望'), (5, 'その他')], default=5),
        ),
        migrations.AddField(
            model_name='company',
            name='place_of_work',
            field=models.ManyToManyField(to='app.placeofwork', verbose_name='就業場所'),
        ),
    ]
